export const PUSH_EMPLOYEE = 'PUSH_EMPLOYEE'
export const PUSH_EMPLOYEE_BY_EMAIL = 'PUSH_EMPLOYEE_BY_EMAIL'
export const PUSH_DELIGATE_IN_EMPLOYEE = 'PUSH_DELIGATE_IN_EMPLOYEE'
export const SELECT_EMPLOYEE = 'SELECT_EMPLOYEE'

export const CREATE_EMPLOYEE_REQUEST = 'CREATE_EMPLOYEE_REQUEST'
export const REMOVE_EMPLOYEE_REQUEST = 'REMOVE_EMPLOYEE_REQUEST'
export const CHANGE_EMPLOYEE_NAME = 'CHANGE_EMPLOYEE_NAME'
export const CHANGE_EMPLOYEE_DEP = 'CHANGE_EMPLOYEE_DEP'
